#include<iostream>
#include<vector>
#include<list>
#include<queue>
using namespace std;

class Graph {
    int V;            
    list<int> *l;  
public:
    Graph(int V) {
        this->V = V;  
        l = new list<int> [V];  
    };

    void addEdge(int u, int v) {
        l[u].push_back(v);  
        l[v].push_back(u);  
    }

    // DFS Traversal
    void dfsHelper(int u, vector<bool> &vis) {
        cout << u << " ";
        vis[u] = true;

        for(int v : l[u]) {
            if(!vis[v]) {
                dfsHelper(v, vis);
            }
        }
    }

    void dfs() {
        int src = 0;
        vector<bool> vis(V, false);
        
        // for disconnected nodes
        // for(int i=0; i<V; i++) {
        //     if(!vis[i]) {
        //         dfsHelper(i, vis);
        //     }
        // }

        dfsHelper(src, vis);
        cout << endl;
    }

};

int main() {
    Graph g(5);

    g.addEdge(0, 2);
    g.addEdge(2, 1);
    g.addEdge(2, 3);
    g.addEdge(2, 4);

    g.dfs();

    return 0;
}